- name: install and start nginx
  hosts: frontend
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
    
  - name: start nginx
  ansible.builin.service:
    name: nginx
    state: started
    enabled: yes